---
name: Github Action custom-docker-image Test
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Install bats core
        run: sh install_bats.sh

      - name: Build the Docker image
        run: docker build -t andes2020/ubuntu:latest .

      - name: Run bat tests
        run: bats test.bat